kotlin.code.style=official
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Enable Gradle Daemon
org.gradle.daemon=true

# Enable parallel builds
org.gradle.parallel=true

# Enable build cache
org.gradle.caching=true

# Enable configuration on demand
org.gradle.configureondemand=true

# Kotlin incremental compilation
kotlin.incremental=true

# Android
android.useAndroidX=true
android.nonTransitiveRClass=true
